config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  
  resources :posts do
    resources :likes
    resources :comments
  end

  devise_for :users
  resources :users, only: [:show], param: :slug
  
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :content
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :thumbnail
  validates_presence_of :content
  validates :thumbnail, presence: true, blob: { content_type: :image }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  def is_admin?
    self.admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    skip_before_action :authenticate_user!, only: :index

    def index
        @@count = params[:count].to_i
        render json: { html: render_to_string(partial: @post.comments.order('id DESC').limit(4 + @@count).drop(2 + @@count)) }
        #render json: { html: params[:count] }
    end

    def show
    end

    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user

        respond_to do |format|
            if @comment.save
                format.html { redirect_to request.referrer, notice: "Comment was successfully created." }
                #format.json { render :show, status: :created, location: post_path(@post) }
            else
                format.html { redirect_to request.referrer, status: :unprocessable_entity }
                #format.html { render :new, status: :unprocessable_entity }
                #format.json { render json: @comment.errors, status: :unprocessable_entity }
            end
        end
    end
  
    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)

        #respond_to do |format|
        #    format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
        #    format.json { head :no_content }
        #end
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:content)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]

    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
        else
            @post.likes.create(user_id: current_user.id)
        end
        #redirect_to post_path(@post)
        redirect_back(fallback_location: root_path)
    end

    def destroy
        if !(already_liked?)
            flash[:notice] = "Cannot unlike"
        else
            @like.destroy
        end
        #redirect_to post_path(@post)
        redirect_back(fallback_location: root_path)
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('id DESC')
    @top = []
    User.all.each do |user|
      @top << {
        user: user,
        counter: user.posts.joins(:likes).count
      }
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @can = @post.user == current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.create(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content, :thumbnail)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  
  def show
    @user = User.where("lower(username) = ?", params[:slug].downcase).first
    @can = @current_user && (@user == current_user || current_user.is_admin?)
    @posts = Post.where(:user_id => @user.id).order('id DESC')
    @avatar = @user.avatar.attached? ? @user.avatar.url(:secure=>true, :width=>256, :height=>256, :crop=>"fill") : "https://via.placeholder.com/128"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(text)
      content_for :title, text
    end

    def yield_meta_tag(tag, default_text='')
        content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
    end

    def meta_tag(tag, text)
        content_for :"meta_#{tag}", text
    end

    def yield_meta_tag(tag, default_text='')
        content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<li class="list-group-item">
    <small><strong><%= comment.user.username %> :</strong> <%= comment.content %></small>
    <div class="d-flex justify-content-between align-items-center">
        <% if current_user && (current_user.is_admin? || comment.user == current_user) %>
            <small><%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></small>
        <% end %>
        <small class="text-muted ms-auto"><%= time_ago_in_words(comment.created_at).capitalize %> ago</small>
    </div>
</li>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="input-group col-sm-10">
    <%= f.text_field :content, placeholder: 'New comment...', required: true, class: 'form-control' %>
    <%= f.submit 'Send', class: 'btn btn-outline-dark' %> 
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= if content_for?(:title) then yield(:title) + ' - ' else 'The MMI social network - ' end %>MMI Fans</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="<%= yield_meta_tag(:description, 'Welcome to MMI Fans, an Instagram remake in Ruby On rails framework for the MMI formation.') %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="canonical" href="<%= request.original_url %>">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:title" content="MMI Fans - The MMI social network">
    <meta property="og:description" content="<%= yield_meta_tag(:description, 'Welcome to MMI Fans, an Instagram remake in Ruby On rails framework for the MMI formation.') %>">
    <meta property="og:image" content="<%= yield_meta_tag(:image, 'https://res.cloudinary.com/hf10ee93o/image/upload/v1621218861/OnlyMMI_bg_qzsyv4.png') %>">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="<%= request.original_url %>">
    <meta property="twitter:title" content="MMI Fans - The MMI social network">
    <meta property="twitter:description" content="<%= yield_meta_tag(:description, 'Welcome to MMI Fans, an Instagram remake in Ruby On rails framework for the MMI formation.') %>">
    <meta property="twitter:image" content="<%= yield_meta_tag(:image, 'https://res.cloudinary.com/hf10ee93o/image/upload/v1621218861/OnlyMMI_bg_qzsyv4.png') %>">
  </head>

  <body>
    <header>
      <div class="d-flex justify-content-between align-items-center container" style="font-size: 1.5rem;">
        <h2>
        <%= link_to :root, title: 'Home' do %>
          <%= image_tag 'https://res.cloudinary.com/hf10ee93o/image/upload/v1621260177/OnlyMMI_d6ymec.png', alt: 'Home button image', class: 'img-fluid', style: 'max-width: 10%;' %>
        <% end %>
        </h2>
        <div class="d-flex gap-4">
          <% if user_signed_in? %>
            <% #@img_profile = current_user.avatar.attached? ? current_user.avatar.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
            <% #image_tag @img_profile, alt: 'Profile picture', class: "rounded-circle me-3", style: 'width: 2rem' %>
            <script>function toggleNotifModal() { document.getElementById('notif-modal').classList.toggle('d-none') }</script>
            <%= button_tag 'button', title: 'Notification', :onclick => 'toggleNotifModal()', class: 'bg-transparent border-0 p-0' do %>
              <i class="far fa-heart"></i>
            <% end %>
            <%= button_to destroy_user_session_path(), title: 'Logout', method: :delete, class: 'bg-transparent border-0 p-0' do %>
                <i class="fas fa-sign-out-alt"></i>
            <% end %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path(), class: 'btn btn-success' %>
            <%= link_to 'Sign in', new_user_session_path(), class: 'btn btn-outline-success' %>
          <% end %>
        </div>
      </div>
    </header>
    <main class="container" style="padding-top: 4rem">
    <div id="notif-modal" class="d-none container position-fixed top left" style="z-index: 100;">
      <div class="row justify-content-end w-100">
        <div class="col-lg-6 bg-light h-50 px-3 shadow-sm rounded" style="overflow-y: scroll; max-height: 50vh">

          <% if current_user %>
            <% @likesNotif = Like.where(post: [current_user.posts]).where.not(user: current_user) %>
            <% @commentsNotif = Comment.where(post: [current_user.posts]).where.not(user: current_user) %>

            <% @totalNotif = @likesNotif + @commentsNotif %>

            <% @totalNotif.sort_by(&:created_at).reverse.each do |notif| %>
              <% @img_notif = notif.user.avatar.attached? ? notif.user.avatar.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
              <% @thumbnail_notif = notif.post.thumbnail.attached? ? notif.post.thumbnail.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
              <div class="d-flex justify-content-between align-items-center my-3">
                <div class="d-flex align-items-center">
                  <a href='/users/<%= notif.user.username %>'>
                    <%= image_tag @img_notif, alt: 'Notif Profile picture', class: "rounded-circle", style: 'width: 2rem;' %>
                  </a>
                  <div class="mx-3">
                    <span>
                    <a href='/users/<%= notif.user.username %>' style="color: inherit; text-decoration: none;">
                      <strong><%= notif.user.username %></strong> 
                    </a>
                    <% if notif.class.name.downcase === 'like' %>
                    like your post 
                    <% elsif notif.class.name.downcase === 'comment' %>
                    comment your post
                    <% end %>
                    <br><small class="text-muted"><%= time_ago_in_words(notif.created_at).upcase %> AGO</small></span>
                  </div>
                </div>
                <a href="<%= post_path(notif.post) %>">
                  <%= image_tag @thumbnail_notif, alt: 'Notif Post Thumbnail', class: "border", style: 'width: 2rem' %>
                </a>
              </div>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs my-3">
    <%= f.input :content, required: true, autofocus: true %>
    <%= f.file_field :thumbnail, required: true, class: 'form-control', 
    accept: 'image/png, image/jpg, image/jpeg' %>
  </div>

  <div class="form-actions my-3">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-6">
        <h1 class="text-center">Editing Post</h1>

        <%= render 'form', post: @post %>
        <%= link_to 'Show', @post, class: 'btn btn-success' %>
        <%= link_to 'Back', posts_path, class: 'btn btn-info' %>
    </div>
</div>

app/views/posts/index.html.erb
<% if false %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1 class="text-center">MMI FANS</h1>

<div class="d-flex justify-content-center row">
    <div class="col-sm-6 d-flex flex-column align-items-center">
        <% @posts.each do |post| %>
            <div class="card mb-5" style="max-width: 32rem">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <a href='/users/<%= post.user.username %>' class='badge bg-light text-dark'>
                        <% @img_rounded = post.user.avatar.attached? ? post.user.avatar.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
                        <%= image_tag @img_rounded, alt: 'Author profile picture', class: "rounded-circle me-2", style: 'width: 2rem' %>
                        <span><%= post.user.username %></span>
                    </a>
                    <small class="text-muted me-1"><%= time_ago_in_words(post.created_at).upcase %> AGO</small>
                </div>
                <% @img = post.thumbnail.url ? post.thumbnail.url(:secure=>true, :width=>1080, :crop=>"fill") : 'https://via.placeholder.com/1080' %>
                <%= image_tag @img, alt: 'Post image', class: "card-img-top" %>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center" style="font-size: 1.5rem;">
                        <div class="d-flex align-items-center" style="gap: 1rem;">
                            <% existing_like = post.likes.find { |like| like.user == current_user } %>
                            <% if existing_like %>
                                <%= button_to post_like_path(post, existing_like), title: 'Unlike', method: :delete, class: 'bg-transparent border-0 p-0' do %>
                                    <i class="fas fa-heart"></i>
                                <% end %>
                            <% else %>
                                <%= button_to post_likes_path(post), title: 'Like', method: :post, class: 'bg-transparent border-0 p-0' do %>
                                    <i class="far fa-heart"></i>
                                <% end %>
                            <% end %>
                            <i class="far fa-comment"></i>
                            <i class="far fa-paper-plane"></i>
                        </div>
                        <i class="far fa-bookmark"></i>
                    </div>
                    <div class="mt-2">
                        <span class="me-3"><%= post.likes.count %> <%= (post.likes.count) <= 1 ? 'like' : 'likes'%></span>
                        <span><%= post.comments.count %> <%= (post.comments.count) <= 1 ? 'comment' : 'comments'%></span>
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= post.user.username %></h5>
                    <p class="card-text"><%= post.content %></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <% if current_user && current_user.is_admin? %>
                            <div class="d-flex" style="gap: 1rem;">
                                <%= link_to 'Show', post, class: 'btn btn-info' %>
                                <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-success' %>
                                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                            </div>
                        <% end %>
                    </div>
                </div>
                <ul id="comment-<%= post.id %>" class="list-group list-group-flush">
                    <% post.comments.order('id DESC').limit(2).each do |comment| %>
                        <%= render comment %>
                    <% end %>
                    <li class="d-flex justify-content-center p-2">
                        <%= button_to post_comments_path(post), title: 'More', method: :get, id: 'more-btn-' + post.id.to_s, class: 'more-com-btn bg-transparent border-0' do %>
                            <i class="far fa-plus-square fs-3"></i>
                        <% end %>
                    </li>
                </ul>
                <div class="card-footer">
                    <%= simple_form_for([post, post.comments.build]) do |f| %>
                        <%= f.error_notification %>
                        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                        <div class="input-group col-sm-10">
                            <%= f.text_field :content, placeholder: 'New comment...', required: true, class: 'form-control' %>
                            <%= f.submit 'Send', class: 'btn btn-outline-dark' %> 
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="col-sm-3">
        <% if current_user %>
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center">
                    <% @img_profile = current_user.avatar.attached? ? current_user.avatar.url(:secure=>true, :width=>64, :height=>64, :crop=>"fill") : 'https://via.placeholder.com/64' %>
                    <%= image_tag @img_profile, alt: 'Profile picture', class: "rounded-circle me-3", style: 'width: 4rem' %>
                    <strong>Welcome <%= current_user.username %>!</strong>
                </div>
            </div>
        <% end %>
        <div class="card">
             <div class="list-group list-group-flush">
                <% @top.sort_by { |t| - t[:counter] }.each do |top| %>
                    <a class="list-group-item list-group-item-action" href='/users/<%= top[:user].username %>'>
                        <% @img_top = top[:user].avatar.attached? ? top[:user].avatar.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
                        <%= image_tag @img_top, alt: 'Author profile picture', class: "rounded-circle me-2", style: 'width: 2rem' %>
                        <%= top[:user].username %> : <%= top[:counter] %> <%= top[:counter] <= 1 ? 'like' : 'likes' %>
                    </a>
                <% end %>
            </div>
        </div>
        <div class="d-flex flex-column align-items-center">
            <%= link_to 'New Post', new_post_path, class: 'btn btn-primary my-4' %>
            <small>© 2021 Maxence Breuilles</small>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-6">
        <h1 class="text-center">New Post</h1>

        <%= render 'form', post: @post %>
        <%= link_to 'Back', posts_path, class: 'btn btn-info' %>
    </div>
</div>

app/views/posts/show.html.erb
<% # Meta information for the <head> section %>
<% title 'Publication' %>
<% meta_tag :description, @post.content %>
<% if @post.thumbnail.attached? %>
    <% meta_tag :image, @post.thumbnail.url(:secure=>true, :width=>1200, :height=>628, :crop=>"fill") %>
<% end %>

<% # View content %>
<h1 class="text-center">Post</h1>
<hr>

<div class="row">
    <div class="col-sm-6">
        <div class="card mb-3" style="max-width: 32rem">
            <% @img = @post.thumbnail.url ? @post.thumbnail.url(:secure=>true, :width=>1080, :crop=>"fill") : 'https://via.placeholder.com/1080' %>
            <%= image_tag @img, class: "card-img-top" %>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <a href='/users/<%= @post.user.username %>' class='badge bg-light text-dark'>
                    <% @img_rounded = @post.user.avatar.attached? ? @post.user.avatar.url(:secure=>true, :width=>32, :height=>32, :crop=>"fill") : 'https://via.placeholder.com/32' %>
                    <%= image_tag @img_rounded, class: "rounded-circle me-2", style: 'width: 2rem' %>
                    <span><%= @post.user.username %></span>
                </a>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center" style="font-size: 1.5rem;">
                    <div class="d-flex align-items-center" style="gap: 1rem;">
                        <% existing_like = @post.likes.find { |like| like.user == current_user } %>
                        <% if existing_like %>
                            <%= button_to post_like_path(@post, existing_like), method: :delete, class: 'bg-transparent border-0 p-0' do %>
                                <i class="fas fa-heart"></i>
                            <% end %>
                        <% else %>
                            <%= button_to post_likes_path(@post), method: :post, class: 'bg-transparent border-0 p-0' do %>
                                <i class="far fa-heart"></i>
                            <% end %>
                        <% end %>
                        <i class="far fa-comment"></i>
                        <i class="far fa-paper-plane"></i>
                    </div>
                    <i class="far fa-bookmark"></i>
                </div>
                <div class="mt-2"><%= @post.likes.count %> <%= (@post.likes.count) <= 1 ? 'like' : 'likes' %></div>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= @post.user.username %></h5>
                <p class="card-text"><%= @post.content %></p>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="card-text m-0"><small class="text-muted"><%= time_ago_in_words(@post.created_at).capitalize %></small></p>
                    <% if (current_user && current_user.is_admin?) || @can %>
                        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-success' %>
                    <% end %>
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <%= render @post.comments %>
            </ul>
            <div class="card-footer">
                <%= render 'comments/form' %>
            </div>
        </div>
    </div>
</div>

<hr>

app/views/users/show.html.erb
<% # Meta information for the <head> section %>
<% title @user.username %>
<% if @user.avatar.attached? %>
    <% meta_tag :image, @user.avatar.url(:secure=>true, :width=>1200, :height=>628, :crop=>"fill") %>
<% end %>

<% # View content %>
<div class="mx-auto" style="max-width: 48rem">

    <section class="d-flex justify-content-center align-items-center">
        <%= image_tag @avatar, class: 'img-thumbnail rounded-circle me-5', style: 'width: 8rem; height: 8rem;' %>
        <div>
            <div class="d-flex align-items-center">
                <h1 class="text-center me-4"><%= @user.username %></h1>
                <%= link_to 'Edit profile', edit_user_registration_path(), class: 'btn btn-outline-dark btn-sm' if @can %>
            </div>
            <div class="d-flex align-items-center">
                <span class="me-4"><strong><%= @posts.count %></strong> <%= (@posts.count) <= 1 ? 'publication' : 'publications' %></span>
                <span><strong><%= @posts.joins(:likes).count %></strong> <%= (@posts.joins(:likes).count) <= 1 ? 'like' : 'likes' %></span>
            </div>
        </div>

    </section>
    <hr>
    <nav class="d-flex justify-content-center align-items-center" style="gap: 4rem">
        <span><i class="fas fa-border-all me-2"></i>PUBLICATIONS</span>
        <span><i class="far fa-bookmark me-2"></i>SAVES</span>
    </nav>
    <hr>

    <div class="feed-container d-flex justify-content-between flex-wrap">
        <% @posts.each do |post| %>
            <a class="mb-3" style="flex: 32%; max-width: 32%;" href="<%= post_path(post) %>">
                <div class="post-container">
                    <% @img = post.thumbnail.url ? post.thumbnail.url(:secure=>true, :width=>512, :height=>512, :crop=>"fill") : 'https://via.placeholder.com/512' %>
                    <%= image_tag @img, class: 'img-fluid' %>
                    <div class="post-hover"><i class="fas fa-heart me-2"></i> <%= post.likes.count %></div>
                </div>
            </a>
        <% end %>
    </div>
</div>